#!/usr/bin/env bash

# Colors

RESET="\e[0m"
BOLD="\e[1m"
DIM="\e[2m"

NEON_BLUE="\e[38;5;39m" 
MAGENTA="\e[38;5;165m"
PINK="\e[38;5;201m"
BLUE="\e[38;5;51m"
PURPLE="\e[38;5;135m"
TEAL="\e[38;5;45m"
RED="\e[38;5;196m"
GREEN="\e[38;5;82m"
YELLOW="\e[38;5;226m"
WHITE="\e[97m"
GRAY="\e[38;5;245m"

# ASCII

detect_distro() {
    local target_distro="${CUSTOM_DISTRO}"
    if [[ -z "$target_distro" ]]; then
        case "$(uname -s)" in
            Linux*)
                if [ -f /etc/os-release ]; then . /etc/os-release; fi
                target_distro="${ID:-unknown}"
                DISTRO="${PRETTY_NAME:-$NAME:-Unknown Linux}"
                ;;
            Darwin*)
                DISTRO="macOS $(sw_vers -productVersion 2>/dev/null || echo "")"
                target_distro="macos"
                ;;
            *)
                DISTRO="Unknown"
                target_distro="unknown"
                ;;
        esac
    else
        case "$target_distro" in
            macos|darwin|mac) DISTRO="macOS" ;;
            *) DISTRO="${target_distro^}" ;;
        esac
    fi

    case "$target_distro" in
                arch|archarm)
                    ART="${BLUE}     ___           __ 
${BLUE}    / _ | ________/ / 
${BLUE}   / __ |/ __/ __/ _ \\
${BLUE}  /_/ |_/_/  \\__/_//_/ "
                    ;;
                cachy|cachyos)
                    ART="${BLUE}    _____         __        ____  ____
${BLUE}   / ___/__ _____/ /  __ __/ __ \\/ __/
${BLUE}  / /__/ _ \\/ __/ _ \\/ // / /_/ /\\ \\  
${BLUE}  \\___/\\_,_/\\__/_//_/\\_, /\\____/___/  
${BLUE}                    /___/             
                    "
                    ;;
                ubuntu)
                    ART="${RED}    __  ____             __      
${RED}   / / / / /  __ _____  / /___ __
${RED}  / /_/ / _ \\/ // / _ \\/ __/ // /
${RED}  \\____/_.__/\\_,_/_//_/\\__/\\_,_/ 
                               "
                    ;;
                debian)
                    ART="${RED}     ___      __   _         
${RED}    / _ \\___ / /  (_)__  ___ 
${RED}   / // / -_) _ \\/ / _ \\/ _ \\
${RED}  /____/\\__/_.__/_/\\_,_/_//_/                           
                    "             
                    ;;
                fedora)
                    ART="${BLUE}     ____       __             
${BLUE}    / __/__ ___/ /__  _______ _
${BLUE}   / _// -_) _  / _ \\/ __/ _ \\/
${BLUE}  /_/  \\__/\\_,_/\\___/_/  \\_,_/ 
                    "
                    ;;
                linuxmint|linux-mint)
                    ART="${GREEN}     __  ____      __ 
${GREEN}    /  |/  (_)__  / /_
${GREEN}   / /|_/ / / _ \\/ __/
${GREEN}  /_/  /_/_/_//_/\\__/ 
"
                    ;;
                zorin|zorinos)
                    ART="${BLUE}   ____           _      ____  ____
${BLUE}  /_  / ___  ____(_)__  / __ \\/ __/
${BLUE}   / /_/ _ \\/ __/ / _ \\/ /_/ /\\ \\  
${BLUE}  /___/\\___/_/ /_/_//_/\\____/___/  
		"
                    ;;
                pop|popos)
                    ART="${BLUE}     ___            ____  ____
${BLUE}    / _ \\___  ___  / __ \\/ __/
${BLUE}   / ___/ _ \\/ _ \\/ /_/ /\\ \\  
${BLUE}  /_/   \\___/ .__/\\____/___/  
${BLUE}           /_/                
                    "                   
                    ;;
                manjaro)
                    ART="${GREEN}     __  ___            _             
${GREEN}    /  |/  /__ ____    (_)__ ________ 
${GREEN}   / /|_/ / _ \\/ _ \\  / / _ \\/ __/ _ \\
${GREEN}  /_/  /_/\\_,_/_//_/_/ /\\_,_/_/  \\___/
${GREEN}                  |___/               
                    "                    ;;
                opensuse*|sles)
                    ART="${GREEN}                       ______  __________
${GREEN}   ___  ___  ___ ___  / __/ / / / __/ __/
${GREEN}  / _ \\/ _ \\/ -_) _ \\_\\ \\/ /_/ /\\ \\/ _/  
${GREEN}  \\___/ .__/\\__/_//_/___/\\____/___/___/  
${GREEN}     /_/                                 
                    "
                    ;;
                slackware)
                    ART="${BLUE}     ______         __                      
${BLUE}    / __/ /__ _____/ /___    _____ ________ 
${BLUE}   _\\ \\/ / _ \\/ __/  '_/ |/|/ / _ \\/ __/ -_)
${BLUE}  /___/_/\\_,_/\\__/_/\\_\\|__,__/\\_,_/_/  \\__/
                    "
                    ;;
                centos|centos-stream|rhel)
                    ART="${RED}    _____         __  ____  ____
${RED}   / ___/__ ___  / /_/ __ \\/ __/
${RED}  / /__/ -_) _ \\/ __/ /_/ /\\ \\  
${RED}  \\___/\\__/_//_/\\__/\\____/___/  
                    "
                    ;;
	mx-linux|mxlinux)
		ART="${BLUE}     __  ___       __   _               
${BLUE}    /  |/  /_ __  / /  (_)__  __ ____ __
${BLUE}   / /|_/ /\\ \\ / / /__/ / _ \\/ // /\\ \\ /
${BLUE}  /_/  /_//_\\_\\ /____/_/_//_/\\_,_//_\\_\\  
		"
		;;
	guix)
		ART="${YELLOW}    _____     _     
${YELLOW}   / ___/_ __(_)_ __
${YELLOW}  / (_ / // / /\\ \\ /
${YELLOW}  \\___/\\_,_/_//_\\_\\ 
		"
		;;
           qubes|qubesos)
		ART="${BLUE}    ____       __           ____  ____
${BLUE}   / __ \\__ __/ /  ___ ___ / __ \\/ __/
${BLUE}  / /_/ / // / _ \\/ -_|_-</ /_/ /\\ \\  
${BLUE}  \\___\\_\\_,_/_.__/\\__/___/\\____/___/  
		"
		;;
	antix)
		ART="${BLUE}              __  _ _  __
${BLUE}   ___ ____  / /_(_) |/_/
${BLUE}  / _ \\/ _ \\/ __/ />  <  
${BLUE}  \\_,_/_//_/\\__/_/_/|_|  
		"
                    ;;
	garuda)
		ART="${RED}    _____                 __    
${RED}   / ___/__ _______ _____/ /__ _
${RED}  / (_ / _ \\/ __/ // / _  / _ \\/
${RED}  \\___/\\_,_/_/  \\_,_/\\_,_/\\_,_/  
		"
		;;
	nobara)
		ART="${MAGENTA}     _  __     __                
${MAGENTA}    / |/ /__  / /  ___ ________ _
${MAGENTA}   /    / _ \\/ _ \\/ _ \\/ __/ _ \\/
${MAGENTA}  /_/|_/\\___/_.__/\\_,_/_/  \\_,_/ 		
		"
		;;
	bazzite)
		ART="${BLUE}     ___              _ __     
${BLUE}    / _ )___ _______ (_) /____ 
${BLUE}   / _  / _ \\/_ /_ // / __/ -_)
${BLUE}  /____/\\_,_//__/__/_/\\__/\\__/
		"
		;;
            kali)
		ART="${NEON_BLUE}     __ __     ___ 
${NEON_BLUE}    / //_/__ _/ (_)
${NEON_BLUE}   / ,< / _ \\/ / / 
${NEON_BLUE}  /_/|_|\\_,_/_/_/  
		"
		;;
	elementaryos|elementary)
		ART="${WHITE}        __                   __                ____  ____
${WHITE}   ___ / /__ __ _  ___ ___  / /____ _______ __/ __ \\/ __/
${WHITE}  / -_) / -_)  ' \\/ -_) _ \\/ __/ _ \\/ __/ // / /_/ /\\ \\  
${WHITE}  \\__/_/\\__/_/_/_/\\__/_//_/\\__/\\_,_/_/  \\_, /\\____/___/  
${WHITE}                                       /___/             
		"
		;;
	kde-neon|kdeneon)
		ART="${BLUE}     __ _____  ____  _  __            
${BLUE}    / //_/ _ \\/ __/ / |/ /__ ___  ___ 
${BLUE}   / ,< / // / _/  /    / -_) _ \\/ _ \\
${BLUE}  /_/|_/____/___/ /_/|_/\\__/\\___/_//_/
		"
		;;
	deepin)
		ART="${BLUE}     ___               _    
${BLUE}    / _ \\___ ___ ___  (_)__ 
${BLUE}   / // / -_) -_) _ \\/ / _ \\
${BLUE}  /____/\\__/\\__/ .__/_/_//_/
${BLUE}              /_/           
		"
		;;
	alpine)
		ART="${NEON_BLUE}     ___   __     _         
${NEON_BLUE}    / _ | / /__  (_)__  ___ 
${NEON_BLUE}   / __ |/ / _ \\/ / _ \\/ -_)
${NEON_BLUE}  /_/ |_/_/ .__/_/_//_/\\__/ 
${NEON_BLUE}         /_/                
		"
		;;
	gobo)
		ART="${BLUE}    _____     __      
${BLUE}   / ___/__  / /  ___ 
${BLUE}  / (_ / _ \\/ _ \\/ _ \\
${BLUE}  \\___/\\___/_.__/\\___/
		"
		;;
                gentoo)
                    ART="${MAGENTA}    _____         __          
${MAGENTA}   / ___/__ ___  / /____  ___ 
${MAGENTA}  / (_ / -_) _ \\/ __/ _ \\/ _ \\
${MAGENTA}  \\___/\\__/_//_/\\__/\\___/\\___/                            
                    "
                    ;;
                endeavour|endeavouros)
                    ART="${MAGENTA}     ____        __                            ____  ____
${MAGENTA}    / __/__  ___/ /__ ___ __  _____  __ ______/ __ \\/ __/
${MAGENTA}   / _// _ \\/ _  / -_) _ \\/ |/ / _ \\/ // / __/ /_/ /\\ \\  
${MAGENTA}  /___/_//_/\\_,_/\\__/\\_,_/|___/\\___/\\_,_/_/  \\____/___/  
                    "
                    ;;
                artix)
                    ART="${BLUE}     ___       __  _     
${BLUE}    / _ | ____/ /_(_)_ __
${BLUE}   / __ |/ __/ __/ /\\ \\ /
${BLUE}  /_/ |_/_/  \\__/_//_\\_\\
                    "    
                    ;;
                void)
                    ART="${GREEN}   _   __     _    __
${GREEN}  | | / /__  (_)__/ /
${GREEN}  | |/ / _ \\/ / _  / 
${GREEN}  |___/\\___/_/\\_,_/  
                    "
                    ;;
                nix|nixos)
                    ART="${BLUE}     _  ___      ____  ____
${BLUE}    / |/ (_)_ __/ __ \\/ __/
${BLUE}   /    / /\\ \\ / /_/ /\\ \\  
${BLUE}  /_/|_/_//_\\_|\\____/___/  
                    "
		;;
macos|darwin|mac)
ART="${MAGENTA}     __  ___         ____  ____
${MAGENTA}    /  |/  /__ _____/ __ \\/ __/
${MAGENTA}   / /|_/ / _ \\/ __/ /_/ /\\ \\  
${MAGENTA}  /_/  /_/\\_,_/\\__/\\____/___/  
"
;;
        *)
            ART="${PINK}
 Unsupported distro :( ${RESET}"
            ;;
    esac
}

# Flags

USE_NERD_FONTS=true
USE_ASCII=true
CUSTOM_DISTRO=""

# Help

show_help() {
    echo ""
    echo -e "${BLUE}Usage:${RESET} synfetch [OPTIONS]"
    echo ""
    echo -e "${BOLD}Options:${RESET}"
    echo -e "  ${PINK}--nonerd${RESET}          Hide icons"
    echo -e "  ${PINK}--noascii${RESET}         Hide ASCII art"
    echo -e "  ${PINK}--distro${RESET} <name>   Display ASCII art of a different distro"
    echo -e "  ${PINK}--live${RESET}            Animated CPU, GPU and RAM usage"
    echo -e "  ${PINK}--help | -h${RESET}       Show this help message"
    echo ""
    echo -e "${BLUE}Available distros:${RESET} arch, cachyos, ubuntu, debian, fedora, linuxmint, zorinos, popos, manjaro, opensuse, slackware, centos, mxlinux, guix, qubesos, antix, garuda, nobara, bazzite, kali, elementaryos, kdeneon, deepin, alpine, gobo, gentoo, endeavouros, artix, void, nixos, macos"
    echo ""
    echo -e "${GRAY}Examples:${RESET}"
    echo -e "  ${GREEN}synfetch ${RESET}"
    echo -e "  ${GREEN}synfetch --live${RESET}"
    echo -e "  ${GREEN}synfetch --nonerd${RESET}"
    echo -e "  ${GREEN}synfetch --noascii${RESET}"
    echo -e "  ${GREEN}synfetch --distro arch${RESET}"
    echo -e "  ${GREEN}synfetch --distro macos --nonerd${RESET}"
    exit 0
}

# Argument Parsing

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
	--live)
		LIVE_MODE=true
		;;
            --nonerd)
                USE_NERD_FONTS=false
                ;;
            --noascii)
                USE_ASCII=false
                ;;
            --distro)
                shift
                CUSTOM_DISTRO="${1,,}"
                ;;
            --help|-h)
                show_help
                ;;
            *)
                echo -e "${PINK}Error:${RESET} Unknown option '$1'"
                echo -e "Run ${PINK}synfetch --help${RESET} for usage"
                exit 1
                ;;
        esac
        shift
    done
}

parse_args "$@"

# Nerd Fonts

if $USE_NERD_FONTS; then
    ICON_OS="󰣇 "
    ICON_KERNEL=" "
    ICON_USER=" "
    ICON_HOST="󰗈 "
    ICON_MOBO=" "
    ICON_CPU=" "
    ICON_GPU="󰾲 "
    ICON_UPTIME=" "
    ICON_SHELL=" "
    ICON_DEWM=" "
    ICON_PKGS="󰏗 "
else
    ICON_OS=""
    ICON_KERNEL=""
    ICON_USER=""
    ICON_HOST=""
    ICON_MOBO=""
    ICON_CPU=""
    ICON_GPU=""
    ICON_UPTIME=""
    ICON_SHELL=""
    ICON_DEWM=""
    ICON_PKGS=""
fi

# CPU & RAM Usage

get_cpu_usage() {
    if [ "$(uname)" = "Linux" ]; then
        read -r cpu user nice system idle iowait irq softirq steal guest guest_nice < /proc/stat
        total1=$((user + nice + system + idle + iowait + irq + softirq + steal + guest + guest_nice))
        idle1=$((idle + iowait))

        sleep 0.2

        read -r cpu user nice system idle iowait irq softirq steal guest guest_nice < /proc/stat
        total2=$((user + nice + system + idle + iowait + irq + softirq + steal + guest + guest_nice))
        idle2=$((idle + iowait))

        diff_total=$((total2 - total1))
        diff_idle=$((idle2 - idle1))
        usage=$((100 * (diff_total - diff_idle) / diff_total))
        echo "$usage"
    else
        top -l 1 | awk '/^CPU usage/ {print int($3)}'
    fi
}

get_ram_usage() {
    if [ "$(uname)" = "Linux" ]; then
        free -m | awk '/Mem:/ {printf "%d", 100*$3/$2}'
    else
        vm_stat | awk '/Pages active/ {print int(($2 * 4096 / 1024 / 1024) / ($(sysctl -n hw.memsize)/1024/1024) * 100)}'
    fi
}

cyber_bar() {
    local percent=$1
    local width=22
    local filled=$((percent * width / 100))
    local bar=""

    local pulse=$(( (percent % 10) + 80 ))

    for ((i=0; i<filled; i++)); do
        if (( i < filled/2 )); then
            bar+="\e[38;5;201m█"
        else
            bar+="\e[38;5;45m█"
        fi
    done

    for ((i=filled; i<width; i++)); do
        bar+="\e[38;5;236m─"
    done

    printf "%b\e[0m %3d%%" "$bar" "$percent"
}

CPU=$(get_cpu_usage)
RAM=$(get_ram_usage)

# GPU & GPU Usage Detector

# get_gpu() {
#    if [ "$(uname)" != "Linux" ]; then
#        echo "$(system_profiler SPDisplaysDataType 2>/dev/null | grep 'Chipset Model' | awk -F': ' '{print $2}' || echo 'Apple GPU')"
#        return
#    fi
#
#    local gpus=()
#
#    if command -v nvidia-smi >/dev/null 2>&1; then
#        while IFS= read -r name; do
#            [ -n "$name" ] && gpus+=("$name")
#        done < <(nvidia-smi --query-gpu=name --format=csv,noheader,nounits 2>/dev/null)
#    fi
#
#    if command -v lspci >/dev/null 2>&1; then
#        while IFS= read -r line; do
#            if [[ "$line" == *"NVIDIA"* ]] && command -v nvidia-smi >/dev/null 2>&1; then
#                continue
#            fi
#
#            name=$(echo "$line" | 
#                   sed 's/^[0-9a-f:.]\+ //' |        
#                   sed 's/^\(VGA compatible controller\|3D controller\|Display controller\): *//' | 
#                   sed 's/ (rev .*)$//' |     
#                   sed 's/ \[.*\]//' )      
#
#            [ -n "$name" ] && gpus+=("$name")
#        done < <(lspci | grep -E 'VGA|3D|Display' 2>/dev/null)
#    fi
#
#    if [ ${#gpus[@]} -eq 0 ]; then
#        if [ -d /sys/class/drm/card0/device ]; then
#            gpus+=("Integrated Graphics")
#        else
#            gpus+=("Unknown GPU")
#        fi
#    fi
#
#    if [ ${#gpus[@]} -gt 0 ]; then
#        printf '%s\n' "${gpus[*]}"
#    else
#        echo "Unknown GPU"
#    fi
#}

get_gpu_usage() {
    if [ "$(uname)" != "Linux" ]; then
        echo "N/A"
        return
    fi

    if command -v nvidia-smi >/dev/null 2>&1; then
        nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits 2>/dev/null | head -n1 | tr -d ' %'
        return
    fi

    if [ -f /sys/class/drm/card0/device/gpu_busy_percent ]; then
        cat /sys/class/drm/card0/device/gpu_busy_percent 2>/dev/null || echo "0"
        return
    fi

    echo "0"
}

# GPU=$(get_gpu)
GPU_USAGE=$(get_gpu_usage)

# Real-time Monitoring

synfetch_live() {
    clear
    tput civis

    trap 'tput cnorm; clear; exit 0' INT

    while true; do
        CPU=$(get_cpu_usage 2>/dev/null || echo 0)
        RAM=$(get_ram_usage 2>/dev/null || echo 0)
        GPU_USAGE=$(get_gpu_usage 2>/dev/null || echo 0)

        tput cup 0 0

        if $USE_ASCII; then
            echo -e "$ART"
            echo
        fi
        echo -e " ${NEON_BLUE}${ICON_OS}${RESET}OS      ${NEON_BLUE}${DISTRO}${RESET}"
        echo -e " ${MAGENTA}${ICON_KERNEL}${RESET}Kernel  ${MAGENTA}$(uname -r)${RESET}"
        echo -e " ${BLUE}${ICON_USER}${RESET}User    ${BLUE}${USER}${RESET}"
        echo -e " ${RED}${ICON_HOST}${RESET}Host    ${RED}$(cat /etc/hostname 2>/dev/null || hostname)${RESET}"
        echo -e " ${GREEN}${ICON_MOBO}${RESET}MoBo    ${GREEN}$(cat /sys/class/dmi/id/board_vendor 2>/dev/null || echo "") $(cat /sys/class/dmi/id/board_name 2>/dev/null || echo "")"${RESET}
        echo -e " ${TEAL}${ICON_CPU}${RESET}CPU     ${TEAL}$(lscpu | grep 'Model name' | awk -F: '{gsub(/^[ \t]+|[ \t]+$/, "", $2); print $2}')${RESET}"
#      echo -e " ${PINK}${ICON_GPU}${RESET}GPU     ${PINK}${GPU}${RESET}"
        echo -e " ${PINK}${ICON_UPTIME}${RESET}Uptime  ${PINK}$(uptime | sed -E 's/^[^,]*up *//; s/, *[0-9]+ users?.*//')${RESET}"
        echo -e " ${PURPLE}${ICON_SHELL}${RESET}Shell   ${PURPLE}${SHELL##*/}${RESET}"
        echo -e " ${GRAY}${ICON_DEWM}${RESET}DE/WM   ${GRAY}${de_wm}${RESET}"
        echo -e " ${YELLOW}${ICON_PKGS}${RESET}Pkgs    ${YELLOW}$(pkg_count)${RESET}"
        echo -e " ${GRAY}────────────────────────────────────────${RESET}"
        echo -e " ${PINK}CPU${RESET}     $(cyber_bar "${CPU}")"
        echo -e " ${PINK}RAM${RESET}     $(cyber_bar "${RAM}")"
        if [[ "$GPU_USAGE" != "N/A" && "$GPU_USAGE" != "0" ]]; then
        echo -e " ${PINK}GPU${RESET}     $(cyber_bar "${GPU_USAGE}")"
        fi
        echo -e " ${GRAY}────────────────────────────────────────${RESET}"
        echo -e " ${DIM}Press Ctrl+C to exit live mode${RESET}                "
        sleep 0.7
    done
} 

# DE/WM Detector

de_wm=""
if [ -n "${XDG_CURRENT_DESKTOP}" ]; then
    de_wm="${XDG_CURRENT_DESKTOP}"
elif [ -n "${DESKTOP_SESSION}" ]; then
    de_wm="${DESKTOP_SESSION}"
else
    de_wm="tty"
    for prog in \
        gnome-shell gnome-session mutter \
        plasmashell kwin_wayland kwin_x11 kded5 kded6 sddm \
        xfwm4 xfce4-session xfce4-panel \
        mate-session marco \
        cinnamon cinnamon-session muffin \
        budgie-wm budgie-panel budgie-session \
        pantheon-session pantheon-shell gala \
        deepin-session dde-desktop dde-dock \
        ukui-session ukui-panel \
        lxsession lxqt-session lxqt-panel openbox \
        enlightenment e17 e16 e22 \
        trinity tde-session \
        unity unity-panel-service \
        cosmic-comp cosmic-session \
        i3 i3wm sway hyprland river wayfire labwc niri dwl \
        awesome bspwm dwm qtile xmonad herbstluftwm spectrwm stumpwm \
        openbox fluxbox blackbox jwm icewm afterstep windowmaker fvwm pekwm \
        twm ctwm metacity sawfish compiz berry hikari cage waybox oxwm exwm; do
        if pgrep -x "$prog" >/dev/null 2>&1; then
            de_wm="$prog"
            break
        fi
    done
fi
case "${de_wm,,}" in
    gnome* | gnome-shell | mutter) de_wm="GNOME" ;;
    plasma* | kde* | plasmashell | kwin* | kded*) de_wm="KDE Plasma" ;;
    xfce* | xfwm4 | xfce4-session) de_wm="XFCE" ;;
    mate* | marco) de_wm="MATE" ;;
    cinnamon* | muffin) de_wm="Cinnamon" ;;
    budgie*) de_wm="Budgie" ;;
    pantheon* | gala) de_wm="Pantheon (elementary OS)" ;;
    deepin* | dde*) de_wm="Deepin DDE" ;;
    ukui*) de_wm="UKUI" ;;
    lxde* | lxsession) de_wm="LXDE" ;;
    lxqt* | lxqt-session) de_wm="LXQt" ;;
    enlightenment | e17 | e16 | e22 | moksha) de_wm="Enlightenment" ;;
    trinity | tde*) de_wm="Trinity (TDE)" ;;
    unity*) de_wm="Unity" ;;
    cosmic*) de_wm="COSMIC (System76)" ;;
    lumina*) de_wm="Lumina" ;;
    i3 | i3wm) de_wm="i3" ;;
    sway) de_wm="Sway" ;;
    hyprland) de_wm="Hyprland" ;;
    river) de_wm="River" ;;
    wayfire) de_wm="Wayfire" ;;
    labwc) de_wm="LabWC" ;;
    niri) de_wm="Niri" ;;
    dwl) de_wm="dwl" ;;
    awesome) de_wm="Awesome" ;;
    bspwm) de_wm="bspwm" ;;
    dwm) de_wm="dwm" ;;
    qtile) de_wm="Qtile" ;;
    xmonad) de_wm="XMonad" ;;
    herbstluftwm) de_wm="herbstluftwm" ;;
    spectrwm) de_wm="spectrwm" ;;
    stumpwm) de_wm="StumpWM" ;;
    openbox) de_wm="Openbox" ;;
    fluxbox) de_wm="Fluxbox" ;;
    blackbox) de_wm="Blackbox" ;;
    jwm) de_wm="JWM" ;;
    icewm) de_wm="IceWM" ;;
    afterstep) de_wm="AfterStep" ;;
    windowmaker | wmaker) de_wm="Window Maker" ;;
    fvwm) de_wm="FVWM" ;;
    pekwm) de_wm="PekWM" ;;
    twm | ctwm) de_wm="TWM" ;;
    metacity) de_wm="Metacity" ;;
    compiz) de_wm="Compiz" ;;
    berry) de_wm="berry" ;;
    hikari) de_wm="Hikari" ;;
    cage) de_wm="Cage (kiosk)" ;;
    waybox) de_wm="Waybox" ;;
    oxwm) de_wm="oxwm" ;;
    exwm) de_wm="exwm" ;; 
    aqua | quartz | macos | darwin) de_wm="macOS (Aqua)" ;;
esac
if [[ "$(uname -s)" == "Darwin" ]]; then
    de_wm="macOS (Aqua)"
fi

if [[ "${de_wm}" == "GNOME" || \
      "${de_wm}" == "KDE Plasma" || \
      "${de_wm}" == "Enlightenment" || \
      "${de_wm}" == "MATE" || \
      "${de_wm}" == "XFCE" || \
      "${de_wm}" == "LXQt" || \
      "${de_wm}" == "Cinnamon" ]]; then
    session_suffix=""
    if [ -n "${XDG_SESSION_TYPE}" ]; then
        case "${XDG_SESSION_TYPE}" in
            wayland) session_suffix=" (Wayland)" ;;
            x11)     session_suffix=" (X11)" ;;
        esac
    elif [ -n "${WAYLAND_DISPLAY}" ]; then
        session_suffix=" (Wayland)"
    elif [ -n "${DISPLAY}" ]; then
        session_suffix=" (X11)"
    fi
    de_wm="${de_wm}${session_suffix}"
fi

# Package Detector

pkg_count() {
    local pkgs=()
    local count

    if command -v dpkg >/dev/null; then
        count=$(dpkg --get-selections | grep -v deinstall | wc -l)
        pkgs+=("$count (dpkg)")

    elif command -v guix >/dev/null; then
        count=$(guix package -I | wc -l)
        pkgs+=("$count (guix)")

    elif command -v rpm >/dev/null; then
        count=$(rpm -qa | wc -l)
        pkgs+=("$count (rpm)")

    elif command -v qlist >/dev/null; then
        count=$(qlist -I | wc -l)
        pkgs+=("$count (portage)")

    elif command -v xbps-query >/dev/null; then
        count=$(xbps-query -l | wc -l)
        pkgs+=("$count (xbps)")

    elif command -v apk >/dev/null; then
        count=$(apk info | wc -l)
        pkgs+=("$count (apk)")

    elif command -v nix-store >/dev/null; then
        count=$(nix-store -q --requisites /run/current-system 2>/dev/null | wc -l || echo 0)
        pkgs+=("$count (nix)")

    elif command -v slackpkg >/dev/null || [ -d /var/log/packages ]; then
        count=$(ls /var/log/packages/ 2>/dev/null | wc -l)
        pkgs+=("$count (slackware)")

    elif command -v brew >/dev/null; then
        local formulas=$(brew list --formula 2>/dev/null | wc -l)
        local casks=$(brew list --cask 2>/dev/null | wc -l)
        pkgs+=("$formulas (formulas) + $casks (casks) = $((formulas + casks)) (brew)")

    elif command -v port >/dev/null; then
        count=$(port -q installed 2>/dev/null | wc -l)
        pkgs+=("$count (MacPorts)")

    elif command -v pkgutil >/dev/null || command -v pkg >/dev/null; then
        count=$(pkgutil --pkgs 2>/dev/null | wc -l)
        pkgs+=("$count (Fink/pkgutil)")

    elif command -v pacman >/dev/null; then
        count=$(pacman -Q | wc -l)
        pkgs+=("$count (pacman)")

    elif command -v flatpak >/dev/null; then
        count=$(flatpak list | wc -l)
        pkgs+=("$count (flatpak)")
        echo "${pkgs[*]}"
        return
    elif ls /Programs >/dev/null 2>&1; then
        count=$(ls /Programs | wc -l)
        pkgs+=("$count (programs)")
    fi

    if command -v flatpak >/dev/null; then
        local fp_count=$(flatpak list | wc -l)
        if [ "$fp_count" -gt 0 ]; then
            pkgs+=("$fp_count (flatpak)")
        fi
    fi

    if [ ${#pkgs[@]} -eq 0 ]; then
        echo "?"
    else
        echo "${pkgs[*]}"
    fi
}

# Main Output

detect_distro

if [[ "${LIVE_MODE:-false}" == true ]]; then
    synfetch_live
else
    if $USE_ASCII; then
        echo -e "$ART"
        echo
    fi

echo -e " ${NEON_BLUE}${ICON_OS}${RESET}OS      ${NEON_BLUE}${DISTRO}${RESET}"
echo -e " ${MAGENTA}${ICON_KERNEL}${RESET}Kernel  ${MAGENTA}$(uname -r)${RESET}"
echo -e " ${BLUE}${ICON_USER}${RESET}User    ${BLUE}${USER}${RESET}"
echo -e " ${RED}${ICON_HOST}${RESET}Host    ${RED}$(cat /etc/hostname 2>/dev/null || hostname)${RESET}"
echo -e " ${GREEN}${ICON_MOBO}${RESET}MoBo    ${GREEN}$(cat /sys/class/dmi/id/board_vendor 2>/dev/null || echo "") $(cat /sys/class/dmi/id/board_name 2>/dev/null || echo "")"${RESET}
echo -e " ${TEAL}${ICON_CPU}${RESET}CPU     ${TEAL}$(lscpu | grep 'Model name' | awk -F: '{gsub(/^[ \t]+|[ \t]+$/, "", $2); print $2}')${RESET}"
# echo -e " ${PINK}${ICON_GPU}${RESET}GPU     ${PINK}${GPU}${RESET}"
echo -e " ${PINK}${ICON_UPTIME}${RESET}Uptime  ${PINK}$(uptime | sed -E 's/^[^,]*up *//; s/, *[0-9]+ users?.*//')${RESET}"
echo -e " ${PURPLE}${ICON_SHELL}${RESET}Shell   ${PURPLE}${SHELL##*/}${RESET}"
echo -e " ${GRAY}${ICON_DEWM}${RESET}DE/WM   ${GRAY}${de_wm}${RESET}"
echo -e " ${YELLOW}${ICON_PKGS}${RESET}Pkgs    ${YELLOW}$(pkg_count)${RESET}"
echo -e " ${GRAY}────────────────────────────────────────${RESET}"
echo -e " ${PINK}CPU${RESET}     $(cyber_bar "${CPU}")"
echo -e " ${PINK}RAM${RESET}     $(cyber_bar "${RAM}")"
if [[ "$GPU_USAGE" != "N/A" && "$GPU_USAGE" != "0" ]]; then
    echo -e " ${PINK}GPU${RESET}     $(cyber_bar "${GPU_USAGE}")"
fi
echo -e " ${GRAY}────────────────────────────────────────${RESET}"
fi
