#!/usr/bin/env bash

# Colors

RESET="\e[0m"
PINK="\e[38;5;201m"
BLUE="\e[38;5;51m"
PURPLE="\e[38;5;135m"
RED="\e[38;5;196m"
GREEN="\e[38;5;40m"
YELLOW="\e[38;5;226m"
MAGENTA="\e[38;5;201m"
WHITE="\e[97m"
GRAY="\e[38;5;245m"

# Theme colors
DRACULA_CYAN="\e[38;5;81m"
DRACULA_PURPLE="\e[38;5;141m"
DRACULA_PINK="\e[38;5;212m"
DRACULA_GREEN="\e[38;5;78m"
DRACULA_YELLOW="\e[38;5;228m"
DRACULA_RED="\e[38;5;203m"
MONO_ACCENT="\e[38;5;51m" 
NORD_ACCENT="\e[38;5;116m" 

# Theme variables

OS_COLOR=""
KERNEL_COLOR=""
USER_COLOR=""
HOST_COLOR=""
MOBO_COLOR=""
CPU_COLOR=""
GPU_COLOR=""
UPTIME_COLOR=""
SHELL_COLOR=""
DEWM_COLOR=""
PKGS_COLOR=""
BAR_LABEL_COLOR=""
FILLED1_COLOR=""
FILLED2_COLOR=""
EMPTY_COLOR=""
SEPARATOR_COLOR=""

# ASCII Detector

detect_distro() {
    local target_distro="${CUSTOM_DISTRO}"
    if [[ -z "$target_distro" ]]; then
        case "$(uname -s)" in
            Linux*)
                if [ -f /etc/os-release ]; then . /etc/os-release; fi
                target_distro="${ID:-unknown}"
                DISTRO="${PRETTY_NAME:-$NAME:-Unknown Linux}"
                ;;
            Darwin*)
                DISTRO="macOS $(sw_vers -productVersion 2>/dev/null || echo "")"
                target_distro="macos"
                ;;
            *)
                DISTRO="Unknown"
                target_distro="unknown"
                ;;
        esac
    else
        case "$target_distro" in
            macos|darwin|mac) DISTRO="macOS" ;;
            *) DISTRO="${target_distro^}" ;;
        esac
    fi

    case "$target_distro" in
                arch|archarm)
                    ART="${BLUE}     ___           __ 
${BLUE}    / _ | ________/ / 
${BLUE}   / __ |/ __/ __/ _ \\
${BLUE}  /_/ |_/_/  \\__/_//_/ "
                    ;;
                cachy|cachyos)
                    ART="${BLUE}    _____         __        ____  ____
${BLUE}   / ___/__ _____/ /  __ __/ __ \\/ __/
${BLUE}  / /__/ _ \\/ __/ _ \\/ // / /_/ /\\ \\  
${BLUE}  \\___/\\_,_/\\__/_//_/\\_, /\\____/___/  
${BLUE}                    /___/             
                    "
                    ;;
                ubuntu)
                    ART="${RED}    __  ____             __      
${RED}   / / / / /  __ _____  / /___ __
${RED}  / /_/ / _ \\/ // / _ \\/ __/ // /
${RED}  \\____/_.__/\\_,_/_//_/\\__/\\_,_/ 
                               "
                    ;;
                debian)
                    ART="${RED}     ___      __   _         
${RED}    / _ \\___ / /  (_)__  ___ 
${RED}   / // / -_) _ \\/ / _ \\/ _ \\
${RED}  /____/\\__/_.__/_/\\_,_/_//_/                           
                    "             
                    ;;
                devuan)
		ART="${RED}     ___                        
${RED}    / _ \\___ _  ____ _____ ____ 
${RED}   / // / -_) |/ / // / _ \\/ _ \\
${RED}  /____/\\__/|___/\\_,_/\\_,_/_//_/
		"
		;;
                fedora)
                    ART="${BLUE}     ____       __             
${BLUE}    / __/__ ___/ /__  _______ _
${BLUE}   / _// -_) _  / _ \\/ __/ _ \\/
${BLUE}  /_/  \\__/\\_,_/\\___/_/  \\_,_/ 
                    "
                    ;;
                linuxmint|linux-mint)
                    ART="${GREEN}     __  ____      __ 
${GREEN}    /  |/  (_)__  / /_
${GREEN}   / /|_/ / / _ \\/ __/
${GREEN}  /_/  /_/_/_//_/\\__/ 
"
                    ;;
                zorin|zorinos)
                    ART="${BLUE}   ____           _      ____  ____
${BLUE}  /_  / ___  ____(_)__  / __ \\/ __/
${BLUE}   / /_/ _ \\/ __/ / _ \\/ /_/ /\\ \\  
${BLUE}  /___/\\___/_/ /_/_//_/\\____/___/  
		"
                    ;;
                pop|popos)
                    ART="${BLUE}     ___            ____  ____
${BLUE}    / _ \\___  ___  / __ \\/ __/
${BLUE}   / ___/ _ \\/ _ \\/ /_/ /\\ \\  
${BLUE}  /_/   \\___/ .__/\\____/___/  
${BLUE}           /_/                
                    "                   
                    ;;
                manjaro)
                    ART="${GREEN}     __  ___            _             
${GREEN}    /  |/  /__ ____    (_)__ ________ 
${GREEN}   / /|_/ / _ \\/ _ \\  / / _ \\/ __/ _ \\
${GREEN}  /_/  /_/\\_,_/_//_/_/ /\\_,_/_/  \\___/
${GREEN}                  |___/               
                    "                    ;;
                opensuse*|sles)
                    ART="${GREEN}                       ______  __________
${GREEN}   ___  ___  ___ ___  / __/ / / / __/ __/
${GREEN}  / _ \\/ _ \\/ -_) _ \\_\\ \\/ /_/ /\\ \\/ _/  
${GREEN}  \\___/ .__/\\__/_//_/___/\\____/___/___/  
${GREEN}     /_/                                 
                    "
                    ;;
                slackware)
                    ART="${BLUE}     ______         __                      
${BLUE}    / __/ /__ _____/ /___    _____ ________ 
${BLUE}   _\\ \\/ / _ \\/ __/  '_/ |/|/ / _ \\/ __/ -_)
${BLUE}  /___/_/\\_,_/\\__/_/\\_\\|__,__/\\_,_/_/  \\__/
                    "
                    ;;
                centos|centos-stream|rhel)
                    ART="${RED}    _____         __  ____  ____
${RED}   / ___/__ ___  / /_/ __ \\/ __/
${RED}  / /__/ -_) _ \\/ __/ /_/ /\\ \\  
${RED}  \\___/\\__/_//_/\\__/\\____/___/  
                    "
                    ;;
	mx-linux|mxlinux)
		ART="${BLUE}     __  ___       __   _               
${BLUE}    /  |/  /_ __  / /  (_)__  __ ____ __
${BLUE}   / /|_/ /\\ \\ / / /__/ / _ \\/ // /\\ \\ /
${BLUE}  /_/  /_//_\\_\\ /____/_/_//_/\\_,_//_\\_\\  
		"
		;;
	guix)
		ART="${YELLOW}    _____     _     
${YELLOW}   / ___/_ __(_)_ __
${YELLOW}  / (_ / // / /\\ \\ /
${YELLOW}  \\___/\\_,_/_//_\\_\\ 
		"
		;;
           qubes|qubesos)
		ART="${BLUE}    ____       __           ____  ____
${BLUE}   / __ \\__ __/ /  ___ ___ / __ \\/ __/
${BLUE}  / /_/ / // / _ \\/ -_|_-</ /_/ /\\ \\  
${BLUE}  \\___\\_\\_,_/_.__/\\__/___/\\____/___/  
		"
		;;
	antix)
		ART="
${BLUE}              __  _ _  __
${BLUE}   ___ ____  / /_(_) |/_/
${BLUE}  / _ \\/ _ \\/ __/ />  <  
${BLUE}  \\_,_/_//_/\\__/_/_/|_|  
		"
                    ;;
	garuda)
		ART="${RED}    _____                 __    
${RED}   / ___/__ _______ _____/ /__ _
${RED}  / (_ / _ \\/ __/ // / _  / _ \\/
${RED}  \\___/\\_,_/_/  \\_,_/\\_,_/\\_,_/  
		"
		;;
	nobara)
		ART="${MAGENTA}     _  __     __                
${MAGENTA}    / |/ /__  / /  ___ ________ _
${MAGENTA}   /    / _ \\/ _ \\/ _ \\/ __/ _ \\/
${MAGENTA}  /_/|_/\\___/_.__/\\_,_/_/  \\_,_/ 		
		"
		;;
	bazzite)
		ART="${BLUE}     ___              _ __     
${BLUE}    / _ )___ _______ (_) /____ 
${BLUE}   / _  / _ \\/_ /_ // / __/ -_)
${BLUE}  /____/\\_,_//__/__/_/\\__/\\__/
		"
		;;
            kali)
		ART="${NEON_BLUE}     __ __     ___ 
${NEON_BLUE}    / //_/__ _/ (_)
${NEON_BLUE}   / ,< / _ \\/ / / 
${NEON_BLUE}  /_/|_|\\_,_/_/_/  
		"
		;;
	elementaryos|elementary)
		ART="        __                   __                ____  ____
   ___ / /__ __ _  ___ ___  / /____ _______ __/ __ \\/ __/
  / -_) / -_)  ' \\/ -_) _ \\/ __/ _ \\/ __/ // / /_/ /\\ \\  
  \\__/_/\\__/_/_/_/\\__/_//_/\\__/\\_,_/_/  \\_, /\\____/___/  
                                       /___/             
		"
		;;
	kde-neon|kdeneon)
		ART="${BLUE}     __ _____  ____  _  __            
${BLUE}    / //_/ _ \\/ __/ / |/ /__ ___  ___ 
${BLUE}   / ,< / // / _/  /    / -_) _ \\/ _ \\
${BLUE}  /_/|_/____/___/ /_/|_/\\__/\\___/_//_/
		"
		;;
	deepin)
		ART="${BLUE}     ___               _    
${BLUE}    / _ \\___ ___ ___  (_)__ 
${BLUE}   / // / -_) -_) _ \\/ / _ \\
${BLUE}  /____/\\__/\\__/ .__/_/_//_/
${BLUE}              /_/           
		"
		;;
	alpine)
		ART="${NEON_BLUE}     ___   __     _         
${NEON_BLUE}    / _ | / /__  (_)__  ___ 
${NEON_BLUE}   / __ |/ / _ \\/ / _ \\/ -_)
${NEON_BLUE}  /_/ |_/_/ .__/_/_//_/\\__/ 
${NEON_BLUE}         /_/                
		"
		;;
	gobo)
		ART="${BLUE}    _____     __      
${BLUE}   / ___/__  / /  ___ 
${BLUE}  / (_ / _ \\/ _ \\/ _ \\
${BLUE}  \\___/\\___/_.__/\\___/
		"
		;;
                lfs|linux-from-scratch)
                    ART="${YELLOW}     __   _                  ____                 ____             __      __ 
${YELLOW}    / /  (_)__  __ ____ __  / __/______  __ _    / __/__________ _/ /_____/ / 
${YELLOW}   / /__/ / _ \\/ // /\\ \\ / / _// __/ _ \\/  ' \\  _\\ \\/ __/ __/ _ \\/ __/ __/ _ \\
${YELLOW}  /____/_/_//_/\\_,_//_\\_\\ /_/ /_/  \\___/_/_/_/ /___/\\__/_/  \\_,_/\\__/\\__/_//_/  
                    "
                    ;;
                gentoo)
                    ART="${MAGENTA}    _____         __          
${MAGENTA}   / ___/__ ___  / /____  ___ 
${MAGENTA}  / (_ / -_) _ \\/ __/ _ \\/ _ \\
${MAGENTA}  \\___/\\__/_//_/\\__/\\___/\\___/                            
                    "
                    ;;
                endeavour|endeavouros)
                    ART="${MAGENTA}     ____        __                            ____  ____
${MAGENTA}    / __/__  ___/ /__ ___ __  _____  __ ______/ __ \\/ __/
${MAGENTA}   / _// _ \\/ _  / -_) _ \\/ |/ / _ \\/ // / __/ /_/ /\\ \\  
${MAGENTA}  /___/_//_/\\_,_/\\__/\\_,_/|___/\\___/\\_,_/_/  \\____/___/  
                    "
                    ;;
                artix)
                    ART="${BLUE}     ___       __  _     
${BLUE}    / _ | ____/ /_(_)_ __
${BLUE}   / __ |/ __/ __/ /\\ \\ /
${BLUE}  /_/ |_/_/  \\__/_//_\\_\\
                    "    
                    ;;
                void)
                    ART="${GREEN}   _   __     _    __
${GREEN}  | | / /__  (_)__/ /
${GREEN}  | |/ / _ \\/ / _  / 
${GREEN}  |___/\\___/_/\\_,_/  
                    "
                    ;;
	bedrock)
	 ART="${GRAY}     ___         __             __  
${GRAY}    / _ )___ ___/ /______  ____/ /__
${GRAY}   / _  / -_) _  / __/ _ \\/ __/   _/
${GRAY}  /____/\\__/\\_,_/_/  \\___/\\__/_/\\_\\                            
		"
		;;
		bodhi)
		ART="${GREEN}     ___          ____   _ 
${GREEN}    / _ )___  ___/ / /  (_)
${GREEN}   / _  / _ \\/ _  / _ \\/ / 
${GREEN}  /____/\\___/\\_,_/_//_/_/  
		"
		;;
                nix|nixos)
                    ART="${BLUE}     _  ___      ____  ____
${BLUE}    / |/ (_)_ __/ __ \\/ __/
${BLUE}   /    / /\\ \\ / /_/ /\\ \\  
${BLUE}  /_/|_/_//_\\_|\\____/___/  
                    "
		;;
          macos|darwin|mac)
                    ART="${MAGENTA}     __  ___         ____  ____
${MAGENTA}    /  |/  /__ _____/ __ \\/ __/
${MAGENTA}   / /|_/ / _ \\/ __/ /_/ /\\ \\  
${MAGENTA}  /_/  /_/\\_,_/\\__/\\____/___/  
"
;;
        *)
            ART="${PINK}
 Unsupported distro :( ${RESET}"
            ;;
    esac
}

# Flags

USE_NERD_FONTS=true
USE_ASCII=true
CUSTOM_DISTRO=""
THEME="synthwave"
LIVE_MODE=false
REFRESH=false

# Theme setter

set_theme() {
    case "$THEME" in
        synthwave)
            OS_COLOR="${BLUE}"
            KERNEL_COLOR="${PURPLE}"
            USER_COLOR="${PINK}"
            HOST_COLOR="${RED}"
            MOBO_COLOR="${GREEN}"
            CPU_COLOR="${BLUE}"
            GPU_COLOR="${PURPLE}"
            UPTIME_COLOR=""
            SHELL_COLOR="${PINK}"
            DEWM_COLOR="${GRAY}"
            PKGS_COLOR="${YELLOW}"
            BAR_LABEL_COLOR="${PINK}"
            FILLED1_COLOR="\e[38;5;201m"   
            FILLED2_COLOR="\e[38;5;45m"
            EMPTY_COLOR="\e[38;5;236m"
            SEPARATOR_COLOR="${GRAY}"
            ;;
        monochrome)
            OS_COLOR="${MONO_ACCENT}"
            KERNEL_COLOR="${MONO_ACCENT}"
            USER_COLOR="${MONO_ACCENT}"
            HOST_COLOR="${MONO_ACCENT}"
            MOBO_COLOR="${MONO_ACCENT}"
            CPU_COLOR="${MONO_ACCENT}"
            GPU_COLOR="${MONO_ACCENT}"
            UPTIME_COLOR="${MONO_ACCENT}"
            SHELL_COLOR="${MONO_ACCENT}"
            DEWM_COLOR="${MONO_ACCENT}"
            PKGS_COLOR="${MONO_ACCENT}"
            BAR_LABEL_COLOR="\e[38;5;245m"
            FILLED1_COLOR="${MONO_ACCENT}"
            FILLED2_COLOR="${MONO_ACCENT}"
            EMPTY_COLOR="\e[38;5;236m"
            SEPARATOR_COLOR="\e[38;5;245m"
            ;;
        minimal)
            MIN_COLOR="\e[38;5;244m"  
            OS_COLOR="${MIN_COLOR}"
            KERNEL_COLOR="${MIN_COLOR}"
            USER_COLOR="${MIN_COLOR}"
            HOST_COLOR="${MIN_COLOR}"
            MOBO_COLOR="${MIN_COLOR}"
            CPU_COLOR="${MIN_COLOR}"
            GPU_COLOR="${MIN_COLOR}"
            UPTIME_COLOR="${MIN_COLOR}"
            SHELL_COLOR="${MIN_COLOR}"
            DEWM_COLOR="${MIN_COLOR}"
            PKGS_COLOR="${MIN_COLOR}"
            BAR_LABEL_COLOR="${GRAY}"
            FILLED1_COLOR="${WHITE}"
            FILLED2_COLOR="${WHITE}"
            EMPTY_COLOR="\e[38;5;236m"
            SEPARATOR_COLOR="${GRAY}"
            ;;
        dracula)
            OS_COLOR="${DRACULA_CYAN}"
            KERNEL_COLOR="${DRACULA_PURPLE}"
            USER_COLOR="${DRACULA_PINK}"
            HOST_COLOR="${DRACULA_GREEN}"
            MOBO_COLOR="${DRACULA_YELLOW}"
            CPU_COLOR="${DRACULA_CYAN}"
            GPU_COLOR="${DRACULA_PURPLE}"
            UPTIME_COLOR=""
            SHELL_COLOR="${DRACULA_PINK}"
            DEWM_COLOR="${GRAY}"
            PKGS_COLOR="${DRACULA_YELLOW}"
            BAR_LABEL_COLOR="${DRACULA_PINK}"
            FILLED1_COLOR="${DRACULA_PINK}"
            FILLED2_COLOR="${DRACULA_CYAN}"
            EMPTY_COLOR="\e[38;5;236m"
            SEPARATOR_COLOR="${GRAY}"
            ;;

           nord)
            OS_COLOR="${NORD_ACCENT}"
            KERNEL_COLOR="${NORD_ACCENT}"
            USER_COLOR="${NORD_ACCENT}"
            HOST_COLOR="${NORD_ACCENT}"
            MOBO_COLOR="${NORD_ACCENT}"
            CPU_COLOR="${NORD_ACCENT}"
            GPU_COLOR="${NORD_ACCENT}"
            UPTIME_COLOR="${NORD_ACCENT}"
            SHELL_COLOR="${NORD_ACCENT}"
            DEWM_COLOR="${NORD_ACCENT}"
            PKGS_COLOR="${NORD_ACCENT}"
            BAR_LABEL_COLOR="${NORD_ACCENT}"
            FILLED1_COLOR="${NORD_ACCENT}"
            FILLED2_COLOR="${NORD_ACCENT}"
            EMPTY_COLOR="\e[38;5;236m"
            SEPARATOR_COLOR="\e[38;5;245m"
            ;;
       esac
}

# Help

show_help() {
    echo ""
    echo -e "${BLUE}Usage:${RESET} synfetch [OPTIONS]"
    echo ""
    echo -e "${BOLD}Options:${RESET}"
    echo -e "  ${PINK}--nonerd${RESET}          Hide icons"
    echo -e "  ${PINK}--noascii${RESET}         Hide ASCII art"
    echo -e "  ${PINK}--distro${RESET} <name>   Display ASCII art of a different distro"
    echo -e "  ${PINK}--live${RESET}            Animated Uptime, CPU, GPU and RAM usage"
    echo -e "  ${PINK}--refresh${RESET}         Force refresh all cache files (use after installing packages)"
    echo -e "  ${PINK}--theme${RESET} <name>    Color theme"
    echo -e "  ${PINK}--help | -h${RESET}       Show this help message"
    echo ""
    echo -e "${BLUE}Available themes:${RESET} synthwave (default), monochrome, minimal, dracula, nord"
    echo -e "${BLUE}Available distros:${RESET} arch, cachyos, ubuntu, debian, devuan, fedora, linuxmint, zorinos, popos, manjaro, opensuse, slackware, centos, mxlinux, guix, qubesos, antix, garuda, nobara, bazzite, kali, elementaryos, kdeneon, deepin, alpine, gobo, lfs, gentoo, endeavouros, artix, void, bedrock, bodhi, nixos, macos"
    exit 0
}

# Argument Parsing

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --live)
                LIVE_MODE=true
                ;;
            --theme)
                shift
                THEME="${1,,}"
                ;;
            --nonerd)
                USE_NERD_FONTS=false
                ;;
            --noascii)
                USE_ASCII=false
                ;;
            --distro)
                shift
                CUSTOM_DISTRO="${1,,}"
                ;;
            --help|-h)
                show_help
                ;;
            --refresh)
                REFRESH=true
                ;;
            *)
                echo -e "${PINK}Error:${RESET} Unknown option '$1'"
                echo -e "Run ${PINK}synfetch --help${RESET} for usage"
                exit 1
                ;;
        esac
        shift
    done
}

parse_args "$@"

# Validate theme

validate_theme() {
    case "$THEME" in
        synthwave|monochrome|minimal|dracula|nord) ;;
        *)
            echo -e "${PINK}Error:${RESET} Unknown theme '$THEME'"
            echo -e "Available: synthwave, monochrome, minimal, dracula, nord"
            exit 1
            ;;
    esac
}
validate_theme
set_theme 

# GPU & GPU Usage Detector

get_gpu() {
    local gpu_list=()
    
    if command -v lspci >/dev/null 2>&1; then
        while read -r line; do
            [[ -n "$line" ]] && gpu_list+=("$line")
        done < <(lspci -nn 2>/dev/null | grep -E 'VGA|3D|Display' | sed 's/.*: //' | sed '
            s/ (rev .*)$//;
            s/\[[0-9a-fx:]\+\]//g;
            s/Advanced Micro Devices, Inc\. \[AMD\/ATI\]/AMD Radeon/;
            s/Advanced Micro Devices, Inc\./AMD/;
            s/Intel Corporation/Intel/;
            s/NVIDIA Corporation/NVIDIA/;
            s/NVIDIA [A-Z0-9]\{2,6\} \[/NVIDIA [/;
            s| / Radeon .* Series||i;
            s/3D controller: //i;
            s/VGA compatible controller: //i;
            s/Display controller: //i;
            s/\[//g; s/\]//g;
            s/ Max-Q//i;
            s/ Laptop//i;
            s/ Mobile//i;
            s/ *\/ *$//;
            s/^ *//; s/ *$//;
        ' | sort -u)
    fi

    if [ ${#gpu_list[@]} -eq 0 ] && command -v nvidia-smi >/dev/null 2>&1; then
        local nvidia_name
        nvidia_name=$(nvidia-smi --query-gpu=name --format=csv,noheader,nounits 2>/dev/null | head -n1)
        [[ -n "$nvidia_name" && "$nvidia_name" != "NVIDIA" ]] && gpu_list+=("NVIDIA $nvidia_name")
    fi

    if [ ${#gpu_list[@]} -gt 0 ]; then
        (IFS=' + '; echo "${gpu_list[*]}")
    else
        if [ -d /sys/class/drm/card0/device ]; then
            local vendor
            vendor=$(cat /sys/class/drm/card0/device/vendor 2>/dev/null)
            case "$vendor" in
                0x10de) echo "NVIDIA GPU" ;;
                0x1002) echo "AMD GPU" ;;
                0x8086) echo "Intel GPU" ;;
                *)      echo "Integrated Graphics" ;;
            esac
        else
            echo "Unknown GPU"
        fi
    fi
}

get_gpu_usage() {
    if [ "$(uname)" != "Linux" ]; then
        echo "N/A"
        return
    fi

    if command -v nvidia-smi >/dev/null 2>&1; then
        local usage
        usage=$(nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits 2>/dev/null | head -n1 | tr -d ' %')
        if [[ "$usage" =~ ^[0-9]+$ ]]; then
            echo "$usage"
            return
        fi
    fi

    local amdgpu_usage=0
    for card in /sys/class/drm/card*/device/gpu_busy_percent; do
        if [ -f "$card" ]; then
            local val
            val=$(cat "$card" 2>/dev/null || echo 0)
            if [[ "$val" =~ ^[0-9]+$ ]] && (( val > amdgpu_usage )); then
                amdgpu_usage=$val
            fi
        fi
    done
    if (( amdgpu_usage > 0 )); then
        echo "$amdgpu_usage"
        return
    fi

       if command -v intel_gpu_top >/dev/null 2>&1; then
        local usage
        usage=$(timeout 0.2s intel_gpu_top -s 500 -o - 2>/dev/null \
                | awk 'NR==3 {print $2; exit}' | tr -d ' %' || echo "0")
        if [[ "$usage" =~ ^[0-9]+$ ]] && (( usage > 0 )); then
            echo "$usage"
            return
        fi
    fi

    echo "0"
}

# CPU Model Detector

get_cpu_model() {
    if [ "$(uname)" = "Darwin" ]; then
        sysctl -n machdep.cpu.brand_string 2>/dev/null || echo "Unknown CPU"
        return
    fi

    if [ -r /proc/cpuinfo ]; then
        local model
        model=$(awk -F': ' '/^model name/ {print $2; exit}' /proc/cpuinfo 2>/dev/null)
        if [ -n "$model" ]; then
            echo "$model" | sed 's/ with Radeon.*//; s/^ *//; s/ *$//'
            return
        fi

        model=$(awk -F': ' '/^Processor/ {print $2; exit}' /proc/cpuinfo 2>/dev/null)
        if [ -n "$model" ]; then
            echo "$model" | sed 's/^ *//; s/ *$//'
            return
        fi

        model=$(awk -F': ' '/^Hardware/ {print $2; exit}' /proc/cpuinfo 2>/dev/null)
        if [ -n "$model" ]; then
            echo "$model" | sed 's/^ *//; s/ *$//'
            return
        fi
    fi

    if command -v lscpu >/dev/null 2>&1; then
        lscpu | grep "^Model name:" | sed 's/.*: *//; s/ with Radeon.*//; s/^ *//; s/ *$//'
        return
    fi

    echo "Unknown CPU"
}

# Package Detector

pkg_count() {
    local pkgs=()
    local count

    if command -v dpkg >/dev/null; then
        count=$(dpkg-query -f '${binary:Package}\n' -W 2>/dev/null | wc -l)
        pkgs+=("$count (dpkg)")
    elif command -v rpm >/dev/null; then
        count=$(rpm -qa 2>/dev/null | wc -l)
        pkgs+=("$count (rpm)")
    elif command -v apk >/dev/null; then
        count=$(apk info -q 2>/dev/null | wc -l)
        pkgs+=("$count (apk)")
    elif command -v xbps-query >/dev/null; then
        count=$(xbps-query -l 2>/dev/null | wc -l)
        pkgs+=("$count (xbps)")
    elif command -v qlist >/dev/null; then
        count=$(qlist -I 2>/dev/null | wc -l)
        pkgs+=("$count (emerge)")
    elif command -v guix >/dev/null; then
        count=$(guix package -I 2>/dev/null | wc -l)
        pkgs+=("$count (guix)")
    elif command -v nix-store >/dev/null; then
        count=$(nix-store -q --requisites /run/current-system 2>/dev/null | wc -l || echo 0)
        pkgs+=("$count (nix)")
    elif command -v slackpkg >/dev/null || [ -d /var/log/packages ]; then
        count=$(ls /var/log/packages/ 2>/dev/null | wc -l)
        pkgs+=("$count (slackware)")
    elif command -v brew >/dev/null; then
        local formulas=$(brew list --formula 2>/dev/null | wc -l)
        local casks=$(brew list --cask 2>/dev/null | wc -l)
        pkgs+=("$formulas (formulas) + $casks (casks) = $((formulas + casks)) (brew)")
    elif command -v port >/dev/null; then
        count=$(port -q installed 2>/dev/null | wc -l)
        pkgs+=("$count (MacPorts)")
    elif command -v pkgutil >/dev/null || command -v pkg >/dev/null; then
        count=$(pkgutil --pkgs 2>/dev/null | wc -l)
        pkgs+=("$count (Fink/pkgutil)")
    elif command -v pacman >/dev/null; then
        count=$(pacman -Qq 2>/dev/null | wc -l)
        pkgs+=("$count (pacman)")
    elif ls /Programs >/dev/null 2>&1; then
        count=$(ls /Programs 2>/dev/null | wc -l)
        pkgs+=("$count (programs)")
    fi

    if command -v flatpak >/dev/null; then
        local fp_count=$(flatpak list 2>/dev/null | wc -l)
        if [ "$fp_count" -gt 0 ]; then
            pkgs+=("$fp_count (flatpak)")
        fi
    fi

    if [ ${#pkgs[@]} -eq 0 ]; then
        echo "?"
    else
        echo "${pkgs[*]}"
    fi
}

# Cache for speed

CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/synfetch"
[[ -d "$CACHE_DIR" ]] || mkdir -p "$CACHE_DIR" 2>/dev/null || true
REFRESH=${REFRESH:-false}

_CACHE_RESULT=""

cache() {
    local key="$1"
    local cmd="$2"
    local ttl="${3:-3600}"
    local cache_file="$CACHE_DIR/${key}.cache"
    local exp_file="$CACHE_DIR/${key}.exp"
    local exp now

    printf -v now '%(%s)T' -1

    exp=0
    [[ -f "$exp_file" ]] && read -r exp < "$exp_file"

    if [[ "$REFRESH" == true ]] || [[ ! -f "$cache_file" ]] || (( now >= exp )); then
        eval "$cmd" > "$cache_file" 2>/dev/null || printf 'Unknown\n' > "$cache_file"
        printf '%d\n' $(( now + ttl )) > "$exp_file"
    fi
    _CACHE_RESULT=$(< "$cache_file")
}

if [[ "$REFRESH" == true ]] || [[ ! -f "$CACHE_DIR/preload.stamp" ]]; then
    cache "cpu"       'get_cpu_model'
    cache "mobo"      'printf "%s %s\n" "$(< /sys/class/dmi/id/board_vendor)" "$(< /sys/class/dmi/id/board_name)" 2>/dev/null'
    cache "gpu"       'get_gpu'
    cache "pkgs"      'pkg_count' 120
    cache "cpu_usage" 'get_cpu_usage' 7
    cache "gpu_usage" 'get_gpu_usage' 7
    touch "$CACHE_DIR/preload.stamp" 2>/dev/null || true
fi

# Preload cached values

cache "cpu"  'get_cpu_model';              CPU_MODEL=$_CACHE_RESULT
cache "mobo" 'printf "%s %s\n" "$(< /sys/class/dmi/id/board_vendor)" "$(< /sys/class/dmi/id/board_name)" 2>/dev/null'; MOBO=$_CACHE_RESULT
cache "gpu"  'get_gpu';                    GPU=$_CACHE_RESULT
cache "pkgs" 'pkg_count' 120;              PKG_COUNT=$_CACHE_RESULT

# CPU Usage & RAM Usage Detector

get_cpu_usage() {
    local stat_cache="$CACHE_DIR/cpu_stat.cache"
    local u n s i io ir so st
    read -r _ u n s i io ir so st _ _ < /proc/stat

    local total=$(( u+n+s+i+io+ir+so+st ))
    local idle=$(( i+io ))

    if [[ -f "$stat_cache" ]]; then
        local pu pn ps pi pio pir pso pst
        read -r pu pn ps pi pio pir pso pst < "$stat_cache"
        local ptotal=$(( pu+pn+ps+pi+pio+pir+pso+pst ))
        local pidle=$(( pi+pio ))
        local dt=$(( total-ptotal ))
        local di=$(( idle-pidle ))
        (( dt > 0 )) && echo $(( (100*(dt-di) + dt/2) / dt )) || echo 0
    else
        echo 0
    fi

    printf '%s %s %s %s %s %s %s %s\n' "$u" "$n" "$s" "$i" "$io" "$ir" "$so" "$st" > "$stat_cache"
}

get_ram_usage() {
    if [ "$(uname)" = "Linux" ]; then
        local key val total=0 avail=0
        while read -r key val _; do
            case $key in
                MemTotal:)     total=$val ;;
                MemAvailable:) avail=$val; break ;;
            esac
        done < /proc/meminfo
        (( total > 0 )) && printf '%d' $(( 100 * (total - avail) / total )) || printf '0'
    else
        vm_stat | awk '/Pages active/ {print int(($2 * 4096 / 1024 / 1024) / ($(sysctl -n hw.memsize)/1024/1024) * 100)}'
    fi
}

RAM=$(get_ram_usage)

# Cyber bar theme

cyber_bar() {
    local percent=$1
    local width=22
    local filled=$((percent * width / 100))
    local bar=""

    for ((i=0; i<filled; i++)); do
        if (( i < filled/2 )); then
            bar+="${FILLED1_COLOR}█"
        else
            bar+="${FILLED2_COLOR}█"
        fi
    done

    for ((i=filled; i<width; i++)); do
        bar+="${EMPTY_COLOR}─"
    done

    [[ "$percent" =~ ^[0-9]+$ ]] || percent=0
    printf "%b\e[0m %3d%%" "$bar" "$percent"
}

if [[ "${LIVE_MODE:-false}" == true ]]; then
    CPU=0
    GPU_USAGE=0
else
    cache "cpu_usage" 'get_cpu_usage' 7; CPU=$_CACHE_RESULT
    cache "gpu_usage" 'get_gpu_usage' 7; GPU_USAGE=$_CACHE_RESULT
fi

# Live Uptime

get_uptime() {
    if [ "$(uname)" = "Linux" ]; then
        local up _
        { read -r up _; } < /proc/uptime
        up=${up%.*} 
    else
        local up=$(sysctl -n kern.boottime 2>/dev/null | awk -F' = ' '{print $2}' | tr -d ',')
        up=$(( $(date +%s) - up ))
    fi

    local days=$((up / 86400))
    local hours=$(( (up % 86400) / 3600 ))
    local mins=$(( (up % 3600) / 60 ))

    local result=""

    (( days > 0 )) && result+="${days}d "
    (( hours > 0 || days > 0 )) && result+="${hours}h "
    result+="${mins}m"

    echo "$result"
}

# Nerd Fonts

if $USE_NERD_FONTS; then
    ICON_OS=" "
    ICON_KERNEL="󰌢 "
    ICON_USER=" "
    ICON_HOST="󰗈 "
    ICON_MOBO="󰟀 "
    ICON_CPU=" "
    ICON_GPU="󰾲 "
    ICON_UPTIME=" "
    ICON_SHELL=" "
    ICON_DEWM=" "
    ICON_PKGS="󰏗 "
else
    ICON_OS=""
    ICON_KERNEL=""
    ICON_USER=""
    ICON_HOST=""
    ICON_MOBO=""
    ICON_CPU=""
    ICON_GPU=""
    ICON_UPTIME=""
    ICON_SHELL=""
    ICON_DEWM=""
    ICON_PKGS=""
fi

# DE/WM Detector 

de_wm="Unknown"

if [ -n "${XDG_CURRENT_DESKTOP}" ]; then
    de_wm="${XDG_CURRENT_DESKTOP}"
elif [ -n "${DESKTOP_SESSION}" ]; then
    de_wm="${DESKTOP_SESSION}"
fi

case "${de_wm,,}" in
    *x-cinnamon*)                    de_wm="Cinnamon" ;;
    *ubuntu:gnome* | zorin:gnome | *gnome*)de_wm="GNOME" ;;
    *kde* | *plasma*)                de_wm="KDE Plasma" ;;
    *xfce*)                          de_wm="XFCE" ;;
    *mate*)                          de_wm="MATE" ;;
    *budgie*)                        de_wm="Budgie" ;;
    *pantheon* | *elementary*)       de_wm="Pantheon" ;;
    *deepin* | *dde*)                de_wm="Deepin DDE" ;;
    *cosmic*)                        de_wm="COSMIC" ;;
    *ukui*)                          de_wm="UKUI" ;;
    *lumina*)                        de_wm="Lumina" ;;
esac

if [[ "$de_wm" == "Unknown" || -z "$de_wm" ]]; then
    de_wm="tty"

    progs_regex="gnome-shell|gnome-session|mutter|plasmashell|kwin_wayland|kwin_x11|kded5|kded6|cinnamon|cinnamon-session|muffin|xfwm4|xfce4-session|xfce4-panel|mate-session|marco|budgie-wm|budgie-panel|budgie-session|pantheon-session|pantheon-shell|gala|deepin-session|dde-desktop|dde-dock|ukui-session|ukui-panel|lxsession|lxqt-session|lxqt-panel|openbox|enlightenment|e17|e16|e22|moksha|trinity|tde-session|unity|unity-panel-service|cosmic-comp|cosmic-session|hyprland|sway|i3|i3wm|river|wayfire|labwc|niri|dwl|awesome|bspwm|dwm|qtile|xmonad|herbstluftwm|spectrwm|stumpwm|fluxbox|blackbox|jwm|icewm|afterstep|windowmaker|fvwm|pekwm|twm|ctwm|metacity|sawfish|compiz|berry|hikari|cage|waybox|oxwm|exwm"

    detected_wm=$(ps -eo comm= 2>/dev/null | grep -E "^(${progs_regex})$" | head -n 1)

    if [[ -n "$detected_wm" ]]; then
        de_wm="$detected_wm"
    fi
fi

case "${de_wm,,}" in
    gnome* | gnome-shell | mutter)          de_wm="GNOME" ;;
    plasma* | kde* | plasmashell | kwin*)   de_wm="KDE Plasma" ;;
    xfce* | xfwm4 | xfce4-session)          de_wm="XFCE" ;;
    mate* | marco)                          de_wm="MATE" ;;
    cinnamon* | muffin)                     de_wm="Cinnamon" ;;
    budgie*)                                de_wm="Budgie" ;;
    pantheon* | gala)                       de_wm="Pantheon" ;;
    deepin* | dde*)                         de_wm="Deepin DDE" ;;
    ukui*)                                  de_wm="UKUI" ;;
    lxde* | lxsession)                      de_wm="LXDE" ;;
    lxqt* | lxqt-session)                   de_wm="LXQt" ;;
    enlightenment | e17 | e16 | e22 | moksha) de_wm="Enlightenment" ;;
    trinity | tde*)                         de_wm="Trinity (TDE)" ;;
    unity*)                                 de_wm="Unity" ;;
    cosmic*)                                de_wm="COSMIC (System76)" ;;
    lumina*)                                de_wm="Lumina" ;;
    i3 | i3wm)                              de_wm="i3" ;;
    sway)                                   de_wm="Sway" ;;
    hyprland)                               de_wm="Hyprland" ;;
    river)                                  de_wm="River" ;;
    wayfire)                                de_wm="Wayfire" ;;
    labwc)                                  de_wm="LabWC" ;;
    niri)                                   de_wm="Niri" ;;
    dwl)                                    de_wm="dwl" ;;
    awesome)                                de_wm="Awesome" ;;
    bspwm)                                  de_wm="bspwm" ;;
    dwm)                                    de_wm="dwm" ;;
    qtile)                                  de_wm="Qtile" ;;
    xmonad)                                 de_wm="XMonad" ;;
    herbstluftwm)                           de_wm="herbstluftwm" ;;
    spectrwm)                               de_wm="spectrwm" ;;
    stumpwm)                                de_wm="StumpWM" ;;
    openbox)                                de_wm="Openbox" ;;
    fluxbox)                                de_wm="Fluxbox" ;;
    blackbox)                               de_wm="Blackbox" ;;
    jwm)                                    de_wm="JWM" ;;
    icewm)                                  de_wm="IceWM" ;;
    afterstep)                              de_wm="AfterStep" ;;
    windowmaker | wmaker)                   de_wm="Window Maker" ;;
    fvwm)                                   de_wm="FVWM" ;;
    pekwm)                                  de_wm="PekWM" ;;
    twm | ctwm)                             de_wm="TWM" ;;
    metacity)                               de_wm="Metacity" ;;
    compiz)                                 de_wm="Compiz" ;;
    berry)                                  de_wm="berry" ;;
    hikari)                                 de_wm="Hikari" ;;
    cage)                                   de_wm="Cage (kiosk)" ;;
    waybox)                                 de_wm="Waybox" ;;
    oxwm)                                   de_wm="oxwm" ;;
    exwm)                                   de_wm="exwm" ;;
esac

if [[ "$(uname -s)" == "Darwin" ]]; then
    de_wm="macOS (Aqua)"
fi

if [[ "${de_wm}" == "GNOME" || "${de_wm}" == "KDE Plasma" || \
      "${de_wm}" == "Cinnamon" || "${de_wm}" == "XFCE" || \
      "${de_wm}" == "MATE" || "${de_wm}" == "LXQt" || \
      "${de_wm}" == "Enlightenment" || "${de_wm}" == "UKUI" ]]; then
    session_suffix=""
    if [ -n "${XDG_SESSION_TYPE}" ]; then
        case "${XDG_SESSION_TYPE}" in
            wayland) session_suffix=" (Wayland)" ;;
            x11)     session_suffix=" (X11)" ;;
        esac
    elif [ -n "${WAYLAND_DISPLAY}" ]; then
        session_suffix=" (Wayland)"
    elif [ -n "${DISPLAY}" ]; then
        session_suffix=" (X11)"
    fi
    de_wm="${de_wm}${session_suffix}"
fi

# Precomputed Variables

{ read -r KERNEL; } < /proc/sys/kernel/osrelease 2>/dev/null || KERNEL=$(uname -r)
: "${HOSTNAME:=$(hostname 2>/dev/null)}"
SHELL_NAME="${SHELL##*/}"

# Real-time Monitoring

synfetch_live() {
    clear
    tput civis

    trap 'tput cnorm; clear; exit 0' INT

    while true; do
        CPU=$(get_cpu_usage 2>/dev/null || echo 0)
        RAM=$(get_ram_usage 2>/dev/null || echo 0)
        GPU_USAGE=$(get_gpu_usage 2>/dev/null || echo 0)

        tput cup 0 0

        if $USE_ASCII; then
            echo -e "$ART"
            echo
        fi

        echo -e " ${OS_COLOR}${ICON_OS}${RESET}OS      ${OS_COLOR}${DISTRO}${RESET}"
        echo -e " ${KERNEL_COLOR}${ICON_KERNEL}${RESET}Kernel  ${KERNEL_COLOR}${KERNEL}${RESET}"
        echo -e " ${USER_COLOR}${ICON_USER}${RESET}User    ${USER_COLOR}${USER}${RESET}"
        echo -e " ${HOST_COLOR}${ICON_HOST}${RESET}Host    ${HOST_COLOR}${HOSTNAME}${RESET}"
        echo -e " ${MOBO_COLOR}${ICON_MOBO}${RESET}MoBo    ${MOBO_COLOR}${MOBO}${RESET}"
        echo -e " ${CPU_COLOR}${ICON_CPU}${RESET}CPU     ${CPU_COLOR}${CPU_MODEL}${RESET}"
        echo -e " ${GPU_COLOR}${ICON_GPU}${RESET}GPU     ${GPU_COLOR}${GPU}${RESET}"
        echo -e " ${UPTIME_COLOR}${ICON_UPTIME}${RESET}Uptime  ${UPTIME_COLOR}$(get_uptime)${RESET}"
        echo -e " ${SHELL_COLOR}${ICON_SHELL}${RESET}Shell   ${SHELL_COLOR}${SHELL_NAME}${RESET}"
        echo -e " ${DEWM_COLOR}${ICON_DEWM}${RESET}DE/WM   ${DEWM_COLOR}${de_wm}${RESET}"
        echo -e " ${PKGS_COLOR}${ICON_PKGS}${RESET}Pkgs    ${PKGS_COLOR}${PKG_COUNT}${RESET}"
        echo -e " ${SEPARATOR_COLOR}────────────────────────────────────────${RESET}"
        echo -e " ${BAR_LABEL_COLOR}CPU${RESET}     $(cyber_bar "${CPU}")"
        echo -e " ${BAR_LABEL_COLOR}RAM${RESET}     $(cyber_bar "${RAM}")"
        if [[ "$GPU_USAGE" != "N/A" && "$GPU_USAGE" != "0" ]]; then
            echo -e " ${BAR_LABEL_COLOR}GPU${RESET}     $(cyber_bar "${GPU_USAGE}")"
        fi
        echo -e " ${SEPARATOR_COLOR}────────────────────────────────────────${RESET}"
        echo -e " ${DIM}Press Ctrl+C to exit live mode${RESET}                "
        sleep 0.4
    done
}

# Main Output

detect_distro

if [[ "${LIVE_MODE:-false}" == true ]]; then
    synfetch_live
else
    if $USE_ASCII; then
        echo -e "$ART"
        echo
    fi

    printf " ${OS_COLOR}${ICON_OS}${RESET}OS      ${OS_COLOR}%s${RESET}\n \
${KERNEL_COLOR}${ICON_KERNEL}${RESET}Kernel  ${KERNEL_COLOR}%s${RESET}\n \
${USER_COLOR}${ICON_USER}${RESET}User    ${USER_COLOR}%s${RESET}\n \
${HOST_COLOR}${ICON_HOST}${RESET}Host    ${HOST_COLOR}%s${RESET}\n \
${MOBO_COLOR}${ICON_MOBO}${RESET}MoBo    ${MOBO_COLOR}%s${RESET}\n \
${CPU_COLOR}${ICON_CPU}${RESET}CPU     ${CPU_COLOR}%s${RESET}\n \
${GPU_COLOR}${ICON_GPU}${RESET}GPU     ${GPU_COLOR}%s${RESET}\n \
${UPTIME_COLOR}${ICON_UPTIME}${RESET}Uptime  ${UPTIME_COLOR}%s${RESET}\n \
${SHELL_COLOR}${ICON_SHELL}${RESET}Shell   ${SHELL_COLOR}%s${RESET}\n \
${DEWM_COLOR}${ICON_DEWM}${RESET}DE/WM   ${DEWM_COLOR}%s${RESET}\n \
${PKGS_COLOR}${ICON_PKGS}${RESET}Pkgs    ${PKGS_COLOR}%s${RESET}\n \
${SEPARATOR_COLOR}────────────────────────────────────────${RESET}\n" \
        "$DISTRO" "$KERNEL" "$USER" "$HOSTNAME" "$MOBO" \
        "$CPU_MODEL" "$GPU" "$(get_uptime)" "$SHELL_NAME" "$de_wm" "$PKG_COUNT"
    printf " ${BAR_LABEL_COLOR}CPU${RESET}     %b\n" "$(cyber_bar "${CPU}")"
    printf " ${BAR_LABEL_COLOR}RAM${RESET}     %b\n" "$(cyber_bar "${RAM}")"
    if [[ "$GPU_USAGE" != "N/A" && "$GPU_USAGE" != "0" ]]; then
        printf " ${BAR_LABEL_COLOR}GPU${RESET}     %b\n" "$(cyber_bar "${GPU_USAGE}")"
    fi
    printf " ${SEPARATOR_COLOR}────────────────────────────────────────${RESET}\n"
fi
